# Generated by Django 3.2.8 on 2021-11-28 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_classes_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='coursePrereqs',
            field=models.CharField(max_length=1024),
        ),
    ]
